version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: pwd
       - run: ls -l
       - run: npm install -D ftp-deploy
       - run: node .circleci/deploy.js

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
